language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: cLXewEnJSDP8W33mCip9+lmBQ2gxsClPHgq0w47YuDOZN8/KL67Y87RA++nuSqP4g5TB+e9iEavg54rqpnoMI5F3ufbpIkG4V7wfMZzeuwKfWS530JJsn7mrb42/zlcKJJ50jaILHy5r9x6L0QSFQqUU0YmFweJSAae7ze8fWb0=
  - secure: ZPGnwe8ViV2Xt03VpXGKMzSRNEhwNxVJ46paLXsMmCUTeDwwYIQbvDSIl/X+oUMREKVXGYmMqe00n3AyhWjXmcEcPGsFnzxq1Z/Sa+B6n1imFzOPuqQJA7HZ4FLxg+Z826HHiNsgSuQhYrQbeWWsGiNJZp2U1yTtv1sY3AbAJ8Y=
  - secure: FlEzultQauQFFHb4j/WwU7sisFvX+/8bj1jUMFKDSqc2HMehdWk901tovWX28Domol0+8qrljsCY++47gjla3RcZeNu9g4KVlDKmG63q22KuWn/0r4fcmKbNqzgElH53keIgaqr/j7BnoKNVwzXoLS1yaiNQn9DZ4xg3DyQZD3A=
  
before_script:
- npm install -g bower
- bower install

script:
- echo 'No test'

before_deploy:
- sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
